language: c
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install gfortran
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install gfortran
        - sudo apt-get install mpich
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install gfortran
        - sudo apt-get install openmpi-bin openmpi-doc libopenmpi-dev
        - ls /usr/lib/openmpi/
        - ls /usr/lib/openmpi/lib/
    - os: osx
      compiler: gcc
      before_install:
        - brew install gcc > /dev/null
        - export FC=gfortran
    - os: windows
      compiler: gcc
      before_install:
           # remove the sh.exe file, which prevents MinGW from working
         - where sh > sh_loc.txt
         - powershell -command "cat sh_loc.txt | rm"
      install:
         - mkdir build
         - cd build
         - cmake -G "MinGW Makefiles" ../
         - mingw32-make VERBOSE=1

install:
  - mkdir build
  - cd build
  - cmake ../
  - make VERBOSE=1

script:
  - ls
  - ./driver_cxx -mdi "-role DRIVER -name driver -method TCP -port 8021" &
  - ./engine_cxx -mdi "-role ENGINE -name MM -method TCP -port 8021 -hostname localhost" &
  - wait
