language: c
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install gfortran
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install gfortran
        - sudo apt-get install mpich
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install gfortran
        - sudo apt-get install openmpi-bin openmpi-doc libopenmpi-dev
        - ls /usr/lib/openmpi/
        - ls /usr/lib/openmpi/lib/
    - os: osx
      compiler: gcc
      before_install:
        - brew install gcc > /dev/null
        - export FC=gfortran
    - os: windows
      compiler: gcc
      before_install:
           # remove the sh.exe file, which prevents MinGW from working
         - where sh > sh_loc.txt
         - powershell -command "cat sh_loc.txt | rm"
      install:
         - mkdir build
         - cd build
         - cmake -G "MinGW Makefiles" ../
         - mingw32-make

         # Copy the .dll files into the binary directory
         - cp lib/mdi/MDI_Library/*.dll* .
         - cp MDI_Test_Codes/STUBS_MPI/*.dll* .


install:
  - mkdir build
  - cd build
  - cmake ../
  - make VERBOSE=1

script:
  - ls

  # Run a CXX-CXX test calculation using TCP/IP
  - ../tests/cxx-cxx_tcp.sh

  # Run a CXX-Fortran test calculation using TCP/IP
  - ../tests/cxx-f90_tcp.sh

  # Run a CXX-Python test calculation using TCP/IP
  - ../tests/cxx-py_tcp.sh

  # Run a Fortran-CXX test calculation using TCP/IP
  - ../tests/f90-cxx_tcp.sh

  # Run a Fortran-Fortran test calculation using TCP/IP 
  - ../tests/f90-f90_tcp.sh

  # Run a Fortran-Python test calculation using TCP/IP
  - ../tests/f90-py_tcp.sh

  # Run a Python-CXX test calculation using TCP/IP
  - ../tests/py-cxx_tcp.sh

  # Run a Python-Fortran test calculation using TCP/IP
  - ../tests/py-f90_tcp.sh

  # Run a Python-Python test calculation using TCP/IP
  - ../tests/py-py_tcp.sh
