language: c
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install gfortran
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install gfortran
        - sudo apt-get install mpich
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install gfortran
        - sudo apt-get install openmpi-bin openmpi-doc libopenmpi-dev
    - os: osx
      compiler: gcc
      before_install:
        - brew install gcc > /dev/null
        - export FC=gfortran
    - os: windows
      compiler: gcc
      before_install:
           # remove the sh.exe file, which prevents MinGW from working
         - where sh > sh_loc.txt
         - powershell -command "cat sh_loc.txt | rm"
         - echo $MDI_CONFIG_OPTIONS
      install:
         # Make Python package build
         - mkdir python_build
         - cd python_build
         - cmake -G "MinGW Makefiles" -Dpython_package=ON ..
         - mingw32-make VERBOSE=1
         - mingw32-make install
         - cd ..
         # Make local install build
         - mkdir build
         - cd build
         - cmake -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX=./install ..
         - mingw32-make VERBOSE=1
         - ls
         - mingw32-make install
         - ls
         - ls MDI_Library
         - curl -L -o test_codes.tar.gz https://github.com/MolSSI/MDI_Test_Codes/archive/v0.1.0.tar.gz
         - tar xvzf test_codes.tar.gz
         - cd MDI_Test_Codes-0.1.0
         - mkdir build
         - cd build
         - ls ~/build/MolSSI/MDI_Library/build/install/include/MDI_Library
         - ls ~/build/MolSSI/MDI_Library/build/install/lib/MDI_Library
         - cmake -Dmdi_include_path=~/build/MolSSI/MDI_Library/build/install/include/MDI_Library -Dmdi_lib_path=~/build/MolSSI/MDI_Library/build/install/lib/MDI_Library -G "MinGW Makefiles" -Dlanguage=Python ..
         - mingw32-make
         - ls
      script:
         - ls
         - find driver_py.py engine_py.py


install:
  # Make Python package build
  - mkdir python_build
  - cd python_build
  - cmake -Dpython_package=ON ..
  - make
  - sudo make install
  - cd ..
  # Make local install build
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=./install ..
  - make
  - make install
  - ls
  - ls MDI_Library
  # Build test codes
  - curl -L -o test_codes.tar.gz https://github.com/MolSSI/MDI_Test_Codes/archive/v0.1.0.tar.gz
  - tar xvzf test_codes.tar.gz
  - cd MDI_Test_Codes-0.1.0
  - mkdir build
  - cd build
  - ls ~/build/MolSSI/MDI_Library/build/install/include/MDI_Library
  - ls ~/build/MolSSI/MDI_Library/build/install/lib/MDI_Library
  - cmake -Dmdi_include_path=~/build/MolSSI/MDI_Library/build/install/include/MDI_Library -Dmdi_lib_path=~/build/MolSSI/MDI_Library/build/install/lib/MDI_Library ..
  - make
  - ls

script:
  - ls
  # Confirm that all executables have been created
  - find driver_cxx engine_cxx driver_f90 engine_f90 driver_py.py engine_py.py
  # Run a CXX-CXX test calculation using TCP/IP
  - ./driver_cxx -mdi "-role DRIVER -name driver -method TCP -port 8021" &
  - ./engine_cxx -mdi "-role ENGINE -name MM -method TCP -port 8021 -hostname localhost" &
  - wait
  # Run a CXX-Fortran test calculation using TCP/IP
  #- ./driver_cxx -mdi "-role DRIVER -name driver -method TCP -port 8021" &
  #- ./engine_f90 -mdi "-role ENGINE -name MM -method TCP -port 8021 -hostname localhost" &
  #- wait
  # Run a CXX-Python test calculation using TCP/IP
  - ./driver_cxx -mdi "-role DRIVER -name driver -method TCP -port 8021" &
  - python engine_py.py -mdi "-role ENGINE -name MM -method TCP -port 8021 -hostname localhost" &
  - wait
  # Run a Fortran-CXX test calculation using TCP/IP
  #- ./driver_f90 -mdi "-role DRIVER -name driver -method TCP -port 8021" &
  #- ./engine_cxx -mdi "-role ENGINE -name MM -method TCP -port 8021 -hostname localhost" &
  #- wait
  # Run a Fortran-Fortran test calculation using TCP/IP
  #- ./driver_f90 -mdi "-role DRIVER -name driver -method TCP -port 8021" &
  #- ./engine_f90 -mdi "-role ENGINE -name MM -method TCP -port 8021 -hostname localhost" &
  #- wait
  # Run a Fortran-Python test calculation using TCP/IP
  #- ./driver_f90 -mdi "-role DRIVER -name driver -method TCP -port 8021" &
  #- python engine_py.py -mdi "-role ENGINE -name MM -method TCP -port 8021 -hostname localhost" &
  #- wait
  # Run a Python-CXX test calculation using TCP/IP
  - python driver_py.py -mdi "-role DRIVER -name driver -method TCP -port 8021" &
  - ./engine_cxx -mdi "-role ENGINE -name MM -method TCP -port 8021 -hostname localhost" &
  - wait
  # Run a Python-Fortran test calculation using TCP/IP
  #- python driver_py.py -mdi "-role DRIVER -name driver -method TCP -port 8021" &
  #- ./engine_f90 -mdi "-role ENGINE -name MM -method TCP -port 8021 -hostname localhost" &
  #- wait
  # Run a Python-Python test calculation using TCP/IP
  - python driver_py.py -mdi "-role DRIVER -name driver -method TCP -port 8021" &
  - python engine_py.py -mdi "-role ENGINE -name MM -method TCP -port 8021 -hostname localhost" &
  - wait
