language: c
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install gfortran
        - sudo pip install -U pytest
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install gfortran
        - sudo apt-get install mpich
        - sudo pip install -U pytest
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install gfortran
        - sudo apt-get install openmpi-bin openmpi-doc libopenmpi-dev
        - sudo pip install mpi4py
        - sudo pip install numpy
        - sudo pip install -U pytest
        - ls /usr/lib/openmpi/
        - ls /usr/lib/openmpi/lib/
      before_script:
        # Run all the tests
        - cd ../tests
        - pytest -k "lib"
        - pytest -l "mpi"
        - cd ../build
    - os: osx
      compiler: gcc
      before_install:
        - brew update > /dev/null
        - brew install gcc > /dev/null
        - export FC=gfortran
        - sudo pip install -U pytest
    - os: windows
      compiler: gcc
      before_install:
         - (new-object System.Net.WebClient).DownloadFile('https://bootstrap.pypa.io/get-pip.py','get-pip.py')
         - ls
         # remove the sh.exe file, which prevents MinGW from working
         - where sh > sh_loc.txt
         - powershell -command "cat sh_loc.txt | rm"
      install:
         - mkdir build
         - cd build
         - cmake -G "MinGW Makefiles" ../
         - mingw32-make

         # Copy the .dll files into the binary directory
         - cp lib/mdi/MDI_Library/*.dll* .
         - cp MDI_Test_Codes/STUBS_MPI/*.dll* .


install:
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=1

script:
  - ls

  # Run a CXX-CXX test calculation using TCP/IP
  - ../tests/cxx-cxx_tcp.sh

  # Run a CXX-Fortran test calculation using TCP/IP
  - ../tests/cxx-f90_tcp.sh

  # Run a CXX-Python test calculation using TCP/IP
  - ../tests/cxx-py_tcp.sh

  # Run a Fortran-CXX test calculation using TCP/IP
  - ../tests/f90-cxx_tcp.sh

  # Run a Fortran-Fortran test calculation using TCP/IP
  - ../tests/f90-f90_tcp.sh

  # Run a Fortran-Python test calculation using TCP/IP
  - ../tests/f90-py_tcp.sh

  # Run a Python-CXX test calculation using TCP/IP
  - ../tests/py-cxx_tcp.sh

  # Run a Python-Fortran test calculation using TCP/IP
  - ../tests/py-f90_tcp.sh

  # Run a Python-Python test calculation using TCP/IP
  - ../tests/py-py_tcp.sh

  - cd ../tests
  - pytest test_mdi.py::test_cxx_cxx_tcp
  - pytest test_mdi.py::test_cxx_f90_tcp
  - pytest test_mdi.py::test_cxx_py_tcp
  - pytest test_mdi.py::test_f90_cxx_tcp
  - pytest test_mdi.py::test_f90_f90_tcp
  - pytest test_mdi.py::test_f90_py_tcp
  - pytest test_mdi.py::test_py_cxx_tcp
  - pytest test_mdi.py::test_py_f90_tcp
  - pytest test_mdi.py::test_py_py_tcp
  - cd ../build
